Pin httpretty to 0.8.10 because 0.8.11 is broken
```
$ ./bin/pip install httpretty
Collecting httpretty
  Using cached httpretty-0.8.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-YjFnpl/httpretty/setup.py", line 98, in <module>
        tests_require=parse_requirements('development.txt'),
      File "/tmp/pip-build-YjFnpl/httpretty/setup.py", line 62, in parse_requirements
        raise RuntimeError("Couldn't find the `requirements.txt' file :(")
    RuntimeError: Couldn't find the `requirements.txt' file :(
```